### Get all users
GET http://localhost:3001/users
Accept: application/json

###

### Create a new user
POST http://localhost:3001/users
Content-Type: application/json

{
  "_id": "674501e73458b5b62347c179",
  "username": "newuser",
  "birthday": "1990-01-01",
  "phone": "1234567890",
  "email": "newuser@example.com",
  "password": "password123"
}

###

### Get user by ID
GET http://localhost:3001/users/674501e73458b5b62347c179
Accept: application/json

###

### Update user by ID
PUT http://localhost:3001/users/674501e73458b5b62347c179
Content-Type: application/json

{
  "username": "updateduser",
  "birthday": "1990-01-01",
  "phone": "0987654321"
}

###

### Delete user by ID
DELETE http://localhost:3001/users/674501e73458b5b62347c179
Accept: application/json